version: '3'
networks:
  laravel:
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-laravel-8
    ports:
        - "8088:80"
    volumes:
        - ./src:/var/www/
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
          - php
          - mysql
    networks:
        - laravel

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
          - "4306:3306"
    volumes:
          - ./mysql:/var/lib/mysql
    environment:
          MYSQL_DATABASE: 127.0.0.1
          MYSQL_USER: root
          MYSQL_PAASWORD: root009
          MYSQL_ROOT_PASSWORD: root009
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
    networks:
            - laravel
  php:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: php-8
      volumes:
          - ./src:/var/www/
      ports:
          - "9000:9000"
      networks:
          - laravel
 